function(configure_linux_static_lib_for_so target)
    if(_LINUX)
        set_property(TARGET ${target} PROPERTY POSITION_INDEPENDENT_CODE ON)
    endif()
endfunction()

function(add_linux_relative_so_search_path relative_path)
    if(_LINUX)
        string(REGEX REPLACE "^[.]?/" "" relative_path "${relative_path}")
        string(REGEX REPLACE "/$" "" relative_path "${relative_path}")
        string(REGEX REPLACE "^[.]$" "" relative_path "${relative_path}")
        if(relative_path STREQUAL "")
            list(APPEND CMAKE_BUILD_RPATH "$ORIGIN")
        else()
            list(APPEND CMAKE_BUILD_RPATH "$ORIGIN/${relative_path}")
        endif()
        set(CMAKE_BUILD_RPATH ${CMAKE_BUILD_RPATH} PARENT_SCOPE)
    endif()
endfunction()
